export const titles = [
  { value: '01', content: 'CHAIRMAN/PRES/COO/CEO/PARTNER' },
  { value: '19', content: 'Assistant to CHAIRMAN/PRES/COO/CEO/PARTNER' },
  { value: '20', content: 'EXEC VP/SR VP/GM/EXEC DIR' },
  { value: '29', content: 'Assistant to EXEC VP/SR VP/GM/EXEC DIR' },
  { value: '30', content: 'CFO/TREASURER/CONTROLLER/CPA' },
  { value: '39', content: 'Assistant to CFO/TREASURER/CONTROLLER/CPA' },
  { value: '40', content: 'OTHER VP/CORP DIRECTORS & MGRS' },
  { value: '49', content: 'Assistant to OTHER VP/CORP DIRECTORS & MGRS' },
  { value: '50', content: 'MGRS-DIRS-COORDINATORS' },
  { value: '59', content: 'Assistant to MGRS-DIRS-COORDINATORS' },
  { value: '60', content: 'SALES DIRECTORS/MGRS/ACCT MGRS' },
  { value: '69', content: 'Assistant to SALES DIRECTORS/MGRS/ACCT MGRS' },
  { value: '70', content: 'PROFESSIONALS' },
  { value: '79', content: 'Assistant to PROFESSIONALS' },
  { value: '80', content: 'MISC TITLES INCL GOVERNMENT' },
  { value: '89', content: 'Assistant to MISC TITLES INCL GOVERNMENT' },
  { value: 'XX', content: 'Other' },
];

export const industries = [
  { value: '43', content: 'Accounting Services' },
  { value: '46', content: 'Advertising/Marketing/Promo/PR' },
  { value: '90', content: 'Agriculture/Forestry/Landscaping' },
  { value: '48', content: 'Architectural Services' },
  { value: '92', content: 'Armed Forces' },
  { value: '60', content: 'Banking/Finance/Brokerage' },
  { value: '51', content: 'Communication  - Not Media' },
  { value: '56', content: 'Computer/Computer Equip Mfg' },
  { value: '54', content: 'Computer/Data Processing Services' },
  { value: '70', content: 'Construction' },
  { value: '45', content: 'Consulting Services' },
  { value: '05', content: 'Educators/Students/Libraries' },
  { value: '47', content: 'Employment Services' },
  { value: '44', content: 'Engineering/Research & Dev Svcs' },
  { value: '80', content: 'Government' },
  { value: '41', content: 'Healthcare Svcs/Assoc' },
  { value: '08', content: 'Homemaker' },
  { value: '61', content: 'Insurance' },
  { value: '57', content: 'Internet/Online Services' },
  { value: '42', content: 'Legal Services/Legal Associations' },
  { value: '53', content: 'Lodging/Hospitality' },
  { value: '55', content: 'Media(Radio/TV/Print)' },
  { value: '10', content: 'Mfg/Printing/Publishing' },
  { value: '95', content: 'Mining' },
  { value: '59', content: 'Non-Profit' },
  { value: '40', content: 'Other Business Services' },
  { value: '62', content: 'Real Estate' },
  { value: '30', content: 'Retail Trade/Restaurants' },
  { value: '49', content: 'Social Services' },
  { value: '58', content: 'Software Design/Development' },
  { value: '50', content: 'Transportation/Logistics' },
  { value: '52', content: 'Utilities(Electric/Gas Waste)' },
  { value: '20', content: 'Wholesale Trade/Distr/Import-Export' },
  { value: 'XX', content: 'Other' },
];
